version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 5000:5000
    networks:
      - red
  backend:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    ports:
      - 5001:5001
    networks:
      - red
  db_boleteria:
    image: mariadb
    hostname: db_boleteria
    environment:
      MYSQL_ROOT_PASSWORD: pf$6#iAEQ#@y7vMnXiTXLLC#wiEHcn
      MYSQL_DATABASE: boleteria
      MYSQL_USER: manager_boleteria
      MYSQL_PASSWORD: RqoKdtp88Z94v7vL#XKVHPxWdb9dw
    volumes:
      - ./Base de datos/boleteria.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - red
volumes:
   data:
     external: false
networks:
    red:
        name: red