# Utiliza una imagen base de Python con Flask
FROM python:3.9-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de requerimientos
COPY Suscription-Backend/requirements.txt ./

RUN pip install --upgrade pip
# Instala las dependencias del backend
RUN apk add --no-cache mariadb-connector-c-dev \
    && apk add --no-cache --virtual .build-deps build-base mariadb-dev \
    && pip install --no-cache-dir -r requirements.txt \
    && apk del .build-deps

RUN apk add --no-cache \
    bash \
    build-base \
    openssl \
    ca-certificates \
    rabbitmq-c-dev 

# Copia el resto de los archivos del backend
COPY Suscription-Backend ./

# Expone el puerto en el que se ejecuta el servidor del backend
EXPOSE 5100

# Expone los puertos de Rabbitmq
EXPOSE 15672
EXPOSE 5672

EXPOSE 3306
# Comando para iniciar el servidor de python
CMD python3 reciber.py
