# Utiliza una imagen base de Python con Flask
FROM python:3.9-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de requerimientos
COPY Suscription-Backend/requirements.txt ./

RUN pip install --upgrade pip
# Instala las dependencias del backend
RUN apk add --no-cache mariadb-connector-c-dev \
    && apk add --no-cache --virtual .build-deps build-base mariadb-dev \
    && pip install --no-cache-dir -r requirements.txt \
    && apk del .build-deps
# Copia el resto de los archivos del backend
COPY Suscription-Backend ./app

# Expone el puerto en el que se ejecuta el servidor del backend
EXPOSE 5100

# Comando para iniciar el servidor de python
CMD python -3 reciber.py
