version: '3'
services:
  nginx:
    image: nginx
    ports:
      - '8088:8088'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - slave0
      - slave1
      - slave2
    networks:
      - red
  garbagecollector:
    build:
      context: ./GarbageCollector
      dockerfile: dockerfile
    depends_on:
      - db_token
    networks:
      - red
  slave0:
    build:
      context: ./token_backend
      dockerfile: dockerfile
      args:
        PORT: $PORT0
        CONFIGFILE: $CONFIGFILE0
    depends_on:
      - db_token
    ports:
      - "5200:5200"
    networks:
      - red
  slave1:
    build:
      context: ./token_backend
      dockerfile: dockerfile
      args:
        PORT: $PORT1
        CONFIGFILE: $CONFIGFILE1
    depends_on:
      - db_token
    ports:
      - "5201:5201"
    networks:
      - red
  slave2:
    build:
      context: ./token_backend/
      dockerfile: dockerfile
      args:
        PORT: $PORT2
        CONFIGFILE: $CONFIGFILE2
    depends_on:
      - db_token
    ports:
      - "5202:5202"
    networks:
      - red
  db_token:
    image: mariadb
    hostname: db_token
    environment:
      MYSQL_ROOT_PASSWORD: fDLb$C^BCx9b&Lxt^ZwFGAXoE2e#8i
      MYSQL_DATABASE: token
      MYSQL_USER: manager_tokens
      MYSQL_PASSWORD: avL#hFVWQCgVjaZDvBSEQ$#VaP5P6Z
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - red
volumes:
   data:
     external: false
networks:
    red:
        name: red