# Utiliza una imagen base de Python con Flask
FROM python:3.9-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de requerimientos
COPY publisher-backend/requirements.txt ./

# Dependencias de rabbitmq

RUN apk add --no-cache \
    bash \
    build-base \
    openssl \
    ca-certificates \
    rabbitmq-c-dev


# Instala las dependencias del backend
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install flask 


# Copia el resto de los archivos del backend
COPY publisher-backend ./


# Expone el puerto en el que se ejecuta el servidor del backend
EXPOSE 5100
EXPOSE 5672 15672

# Comando para activar el entorno de Flask
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5100

# Comando para iniciar el servidor de Flask
CMD flask run --host=$FLASK_RUN_HOST --port=$FLASK_RUN_PORT
