# Utiliza una imagen base de Python con Flask
FROM python:3.9-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de requerimientos
COPY Backend/requirements.txt ./

# Instala las dependencias del backend
RUN apk add --no-cache mariadb-connector-c-dev \
    && apk add --no-cache --virtual .build-deps build-base mariadb-dev \
    && pip install --no-cache-dir -r requirements.txt \
    && apk del .build-deps

# Copia el resto de los archivos del backend
COPY Backend ./

# Instala el entorno de Flask
RUN pip install flask

# Expone el puerto en el que se ejecuta el servidor del backend
EXPOSE 5001

# Comando para activar el entorno de Flask
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5001

# Comando para iniciar el servidor de Flask
CMD flask run --host=$FLASK_RUN_HOST --port=$FLASK_RUN_PORT
